# Generated by Django 5.2 on 2025-04-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_alter_course_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
